kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: kilbiller/remyperu.fr
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - "${DRONE_BRANCH}"
        - "${DRONE_COMMIT_SHA:0:7}"
        - "${DRONE_TAG:=${DRONE_BRANCH}}"
      cache_from:
        - "kilbiller/remyperu.fr:master"
        - "kilbiller/remyperu.fr:${DRONE_BRANCH}"
