kind: pipeline
name: default

steps:
  - name: lint
    image: node:10-alpine
    commands:
      - yarn install
      - yarn run lint

  - name: build
    image: plugins/docker
    settings:
      repo: kilbiller/remyperu.fr
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - "${DRONE_BRANCH:=latest}"
        - "${DRONE_COMMIT_SHA:0:7}"
        - "${DRONE_TAG:=latest}"
      cache_from:
        - "kilbiller/remyperu.fr:master"
        - "kilbiller/remyperu.fr:${DRONE_BRANCH}"

  - name: build_kustomize_config
    image: bitlayer/kustomize:v2.0.3
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - kustomize build k8s/production > /tmp/cache/deploy.yml
    when:
      event:
        - tag

  - name: deploy
    image: lachlanevenson/k8s-kubectl:v1.13.4
    volumes:
      - name: cache
        path: /tmp/cache
    environment:
      KUBECONF:
        from_secret: kubeconf
    commands:
      - echo $KUBECONF > kube.conf
      - cat kube.conf
      - kubectl --kubeconfig kube.conf get pods
      - kubectl --kubeconfig kube.conf apply -f /tmp/cache/deploy.yml
    when:
      event:
        - tag

volumes:
  - name: cache
    temp: {}
