kind: pipeline
name: default

steps:
  - name: lint
    image: node:10-alpine
    commands:
      - yarn install
      - yarn run lint

  - name: build
    image: plugins/docker
    settings:
      repo: kilbiller/remyperu.fr
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - "${DRONE_BRANCH:=latest}"
        - "${DRONE_COMMIT_SHA:0:7}"
        - "${DRONE_TAG:=latest}"
      cache_from:
        - "kilbiller/remyperu.fr:master"
        - "kilbiller/remyperu.fr:${DRONE_BRANCH}"

  - name: build_kustomize_config
    image: bitlayer/kustomize:v2.0.3
    commands:
      - kustomize build k8s/production > deploy.yml
    when:
      event:
        - tag

  - name: deploy
    image: lachlanevenson/k8s-kubectl:v1.13.4
    environment:
      KUBECONF:
        from_secret: kubeconf
    commands:
      - echo ${KUBECONF} > /root/.kube/config
      - kubectl apply -f deploy.yml
    when:
      event:
        - tag
