apiVersion: apps/v1
kind: Deployment
metadata:
  name: remyperu-web
spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - remyperu-web
            topologyKey: "kubernetes.io/hostname"
