apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - remyperu.dev-ing.yaml
  - remyperu.fr-ing.yaml
  - ../../base

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: kilbiller/remyperu.fr
    newTag: v4.2.1

patchesStrategicMerge:
  - app-deploy.yaml
