apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - remyperu.dev-ing.yaml
  - remyperu.fr-ing.yaml
  - app-networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge:
  - app-deploy.yaml
