apiVersion: v1
kind: Service
metadata:
  name: remyperu-web
  labels:
    app.kubernetes.io/name: remyperu-web
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: remyperu-web
