apiVersion: apps/v1
kind: Deployment
metadata:
  name: remyperu-web
  labels:
    app.kubernetes.io/name: remyperu-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: remyperu-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: remyperu-web
    spec:
      containers:
        - name: remyperu-web
          image: "kilbiller/remyperu.fr:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.01"
            limits:
              memory: "500Mi"
              cpu: "0.5"
