name: ci

on:
  push:
    tags:
      - '**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: kilbiller/remyperu.fr:${{ steps.get-tag.outputs.tag }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
