name: ci

on:
  push:
    tags:
      - '**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: kilbiller/remyperu.fr:${{ steps.get-tag.outputs.tag }}
          push: true
          cache-from: type=gha,scope=amd64
          cache-to: type=gha,mode=max,scope=amd64

      - name: Build and push (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          tags: kilbiller/remyperu.fr:${{ steps.get-tag.outputs.tag }}
          push: true
          cache-from: type=gha,scope=arm64
          cache-to: type=gha,mode=max,scope=arm64

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update kustomize config with latest image
        run: |
          cd k8s/overlays/production
          kustomize edit set image kilbiller/remyperu.fr:${{ steps.get-tag.outputs.tag }}

      - name: Setup kubectl
        uses: ThomasKliszowski/setup-kubectl@v1
        with:
          kube-config: ${{ secrets.KUBECONFIG }}
          kube-version: 1.23.0

      - name: Deploy app
        run: |
          kustomize build k8s/overlays/production | kubectl apply -f -
